/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neojet_scanner_key */

#ifndef _Included_com_topeet_adctest_adc
#define _Included_com_topeet_adctest_adc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_topeet_adctest_adc
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_adctest_adc_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_adctest_adc
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_adctest_adc_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_adctest_adc
 * Method:    Ioctl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_adctest_adc_Ioctl
  (JNIEnv *, jobject, jint num, jint en);

/*
 * Class:     com_topeet_adctest_adc
 * Method:    Read
 * Signature: ()I
 */
JNIEXPORT jintArray JNICALL Java_com_topeet_adctest_adc_Read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
